# Methods

## DEMs

DEMs were obtained for two small sample areas in South Australia:

* Bakara. An area in the Murray Mallee with jumbled dunes, east-west dunes and flat areas
* Woakwine. An area to the south of the Coorong in the southeast of South Australia. This area rises gently from a lake, to subtle hills through which a trench runs.

Both area have a mix of native vegetation and agricultural land.

Table \@ref(tab:DEMs) lists the available DEMs, include the 'short' name used throughout the document.

```{r DEMs}

  rasters %>%
    dplyr::mutate(reference = as.logical(ref_flag)
                  , source = NA
                  , licence = NA
                  ) %>%
    dplyr::arrange(area, short) %>%
    dplyr::select(area
                  , file = name
                  , `short name` = short
                  , reference
                  , `original resolution (cm)` = original_cm
                  , source
                  , licence
                  ) %>%
    kableExtra::kable(caption = paste0("Sample DEMs")
                      , format.args = list(digits = 2)
                      ) %>%
    kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))


```


## Processing

For each DEM, the following workflow was applied:

* reprojected into GDA 2020
* masked to the minimum available overlap between all DEMs (in each area)
* aggregated or disaggregated to roughly 10 m from original resolution
* reprojected into the same `r terra::res(samples$ras[[1]])[1]` m raster
* processed by the `Qfit` function in the `MultiscaleDTM` package `r envReport::cite_package("MultiscaleDTM")` using two values for the `v` argument (window size): `r windows$window %>% envFunc::vec_to_sentence()` cells

The `Qfit` function generates several continuous and one categorical variable for a digital terrain model:

* `r paste0(as.character(formals(MultiscaleDTM::Qfit)$metrics)[-1], collapse = "\n* ")``

A [shiny app](https://ailich.shinyapps.io/Terrain_Attributes_Explorer_App/) is available to investigate the meaning of each of these variables.

Each of the `Qfit` metrics was sampled `r settings$sample_n` times. The samples were used to generate a range of visualisations and summary statistics.

