---
title: DEM comparison
author:
- Nigel Willoughby
- Department for Environment and Water
date: "`r format(Sys.time(), '%A, %d %B, %Y. %H:%M')`"
link-citations: yes
bibliography: packages.bib
description: "This work aims to compare digital terrain models as potential inputs to ecosystem modelling."
---

```{r setup, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE}

  repo_link <- gsub("\\.git$", "", usethis::git_remotes()$origin)

  #------Bibliography-------
  
  url <- "https://raw.githubusercontent.com/citation-style-language/styles/master/emu-austral-ornithology.csl"
  download.file(url, "../common/bib_style.csl")
  
  unlink("packages.bib")
  
  
  #--------knitr options--------
  
  knitr::opts_knit$set(eval.after = "fig.cap")
  
  
  #-------chunk options-------

  knitr::opts_chunk$set(echo = FALSE
                        , warning = FALSE
                        , error = FALSE
                        , message = FALSE
                        , tidy = TRUE
                        , tidy.opts = list(comment = FALSE)
                        #, dpi = 300
                        #, fig.width = 7
                        )

  
  #--------options-------

  options(knitr.kable.NA = ""
          , knitr.duplicate.label = "allow"
          )


  #------citations--------

  # knitcitations::cleanbib()
  # options("citation_format" = "pandoc")
  
  
  #-------Rmd--------
  
  tmap::tmap_mode("plot")
  
  tmap::tmap_options(basemaps = c("OpenStreetMap.Mapnik"
                                  , "Esri.WorldImagery"
                                  )
                     , limits = c(facets.view = 16)
                     )

```

```{r stuff}

  if(!exists("categ")) source("sampleDEM.R")

```

```{r bbox}

  if(settings$area == "Bakara") {
    
    bbox <- sf::st_bbox(c(xmin = 139.981142
                          , ymin = -34.565524
                          , xmax = 139.955216
                          , ymax = -34.58927
                          )
                        , crs = 4326
                        ) %>%
      sf::st_as_sfc() %>%
      sf::st_transform(crs = sf::st_crs(samples$ras[[1]]))
    
  } else if(settings$area == "Woakwine"){
    
    bbox <- sf::st_bbox(c(xmin = 140.029951
                          , ymin = -37.390504
                          , xmax = 140.044338
                          , ymax = -37.383261
                          )
                        , crs = 4326
                        ) %>%
      sf::st_as_sfc() %>%
      sf::st_transform(crs = sf::st_crs(samples$ras[[1]]))
    
    
  } else {
    
    bbox <- sf::st_bbox(samples$ras[[1]])
    
  }

```

# Intro

`r `

To model ecosystems, the terrain model should be able to distinguish changes in elevation in the order of a few metres above the surrounding area. For example in mallee, dunes a couple of metres high and 10s of metres wide often have different vegetation to the swales between the dunes. Swales can be 100s to 1000s of metres wide.

