
```{r thisOne{{areaID}}}

  areaID <- "{{areaID}}"

```

```{r dataCont{{areaID}}}

cont_area <- cont %>%
  dplyr::filter(aoi_id == areaID)

use_name <- unique(cont_area$aoi_name)

reference <- results_df %>%
  dplyr::filter(aoi_id == areaID
                , is_ref
                ) %>%
  dplyr::pull(dem_name)

terr <- l[results_df$aoi_id == areaID] |>
  purrr::map(\(x) {
    
    levels(x) <- data.frame(ID = terra::values(x) |> as.vector() |> unique() |> sort()) %>%
      dplyr::mutate(category = c("canyon", 
                                 "midslope drainage", "upland drainage", "u-shaped valley", 
                                 "plains", "open slopes", "upper slopes", "local ridges", 
                                 "midslopes ridges", "mountain tops")[.$ID]
      )
    
    return(x)
    }
    ) |>
  terra::rast() |>
  setNames(paste0(results_df$dem_name[results_df$aoi_id == areaID]))

```

# `r use_name`

## Continuous

```{r cont_metric_rmd{{areaID}}}

  cont_metric_rmd <- NULL

  # this loops through cont_metric.Rmd, generating the results for each report card

  for (i in unique(cont_area$metric)) {
    
    cont_metricID <- i
    
    cont_metric_rmd <- c(cont_metric_rmd
                         , knit_expand(here::here("report"
                                                  , "child"
                                                  , "cont_metric.Rmd"
                                                  )
                                       )
                         )
    
  }

```

`r paste(knit(text = cont_metric_rmd), collapse = '\n')`

## Categorical

Table \@ref(tab:categTab{{areaID}}) shows the proportion of each DEM classifed to each landform element (also see Figure \@ref(fig:categCount{{areaID}}).

Figure \@ref(fig:categ{{areaID}}) shows a landscape classification for each reprojected area.

```{r categTab{{areaID}}}

categ_area <- categ %>%
  dplyr::filter(aoi_id == areaID) |>
  dplyr::distinct()

categ_area %>%
  dplyr::select(dem_name
                , category
                , prop
                ) %>%
  dplyr::left_join(tibble::tibble(category = 1:10
                                  , landform = c("canyon", 
                                          "midslope drainage", "upland drainage", "u-shaped valley", 
                                          "plains", "open slopes", "upper slopes", "local ridges", 
                                          "midslopes ridges", "mountain tops")
                                  )
                   ) |>
  dplyr::select(-category) |>
  tidyr::pivot_wider(names_from = dem_name, values_from = prop) %>%
  dplyr::select(landform, !!rlang::ensym(reference), everything()) |>
  kableExtra::kable(caption = paste0("Proportion of "
                                     , use_name
                                     , " area classified to each landform element"
                                     )
                    , format.args = list(digits = 2)
                    , format = "html"
                    ) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

```

<br>

```{r categ{{areaID}}, fig.cap = paste0("Categorical representation of ", use_name)}

m <- tm_shape(terr) +
  tm_raster(col.scale = tm_scale_categorical(values = "viridis")
            , col.legend = tm_legend(position = tm_pos_out("right", "top", pos.h = "center"))
            ) +
  tm_facets(nrow = 2)

m <- tmap::tmap_leaflet(m)

class(m) <- c(class(m), "htmlwidget")

m

```

```{r categCount{{areaID}}, fig.cap = paste0("Proportion of categorised ", use_name, " area in each of several classification classes")}

  ggplot(categ_area %>%
           dplyr::filter(aoi_id == areaID) |>
           dplyr::mutate(dem_name = forcats::fct_relevel(dem_name, reference))
         , aes(category, prop, fill = dem_name)
         ) +
    geom_col(position = "dodge") +
    #facet_grid(~ window) +
    coord_flip() +
    scale_fill_viridis_d() +
    guides(fill = guide_legend(reverse = TRUE))

```
